### ISSUE TITLE
Check next

### ISSUE THREAD

**Issue by catalin-hritcu** [FStarLang/fstar-interactive#3]
Any chance for another key shortcut `Ctrl+Shift+N` that advances the checking to the next top level definitions. Without this it's not so convenient to always go to the end of a large definition in order to re-check it.

**Comment by aseemr** [comment]
Please see commit https://github.com/FStarLang/fstar-interactive/commit/403c29ee7b5f7cac925de7b9a86f69b659fadb11. I have tested on mac and seems to work fine.
